version: "3"
services:
  jenkins:
    container_name: jenkins
    user: root
    image: jenkinsci/blueocean
    restart: on-failure
    ports:
      - "8080:8080"
      - "50000:50000"
    network_mode: host
    volumes:
      - /root/.m2:/root/.m2
      - /etc/localtime:/etc/localtime:ro
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: -Duser.timezone=Asia/Shanghai
  registry-srv:
    container_name: registry-srv
    image: registry:2
    ports:
      - 5000:5000
    restart: on-failure
    volumes:
      - /mnt/registry:/var/lib/registry
      - $HOME/auth:/auth
    environment:
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
  registry-ui:
    container_name: registry-ui
    image:  joxit/docker-registry-ui:static
    restart: on-failure
    ports:
      - 80:80
    environment:
      REGISTRY_URL: http://registry-srv:5000
      DELETE_IMAGES: "true"
      REGISTRY_TITLE: My registry

networks:
  default:
    driver: bridge
