version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    restart: on-failure
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.3.2
    restart: on-failure
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.3.2
    restart: on-failure
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    volumes:
      - "/devops/elk/cnf/pipeline/:/usr/share/logstash/pipeline/"
    environment:
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.3.2
    restart: on-failure
    depends_on:
      - logstash
    volumes:
      - "/devops/elk/cnf/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/data/home/:/data/home/"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      setup.kibana.host: kibana:5601
      output.elasticsearch.hosts: '["elasticsearch:9200"]'
